insert into model (id, model, brend, color) values (1, 1995, 'LS', 'Crimson');
insert into model (id, model, brend, color) values (2, 2009, 'Q7', 'Teal');
insert into model (id, model, brend, color) values (3, 2007, 'Aura', 'Goldenrod');
insert into model (id, model, brend, color) values (4, 1987, 'E-Series', 'Pink');
insert into model (id, model, brend, color) values (5, 2004, 'Sentra', 'Green');
insert into model (id, model, brend, color) values (6, 2006, 'GX', 'Mauv');
insert into model (id, model, brend, color) values (7, 1988, 'Excel', 'Violet');
insert into model (id, model, brend, color) values (8, 1967, 'LeMans', 'Puce');
insert into model (id, model, brend, color) values (9, 1995, 'Sephia', 'Puce');
insert into model (id, model, brend, color) values (10, 1969, 'Roadrunner', 'Yellow');
insert into model (id, model, brend, color) values (11, 1998, 'Avalon', 'Pink');
insert into model (id, model, brend, color) values (12, 1988, 'Tempo', 'Indigo');
insert into model (id, model, brend, color) values (13, 2009, 'Suburban 1500', 'Teal');
insert into model (id, model, brend, color) values (14, 2001, 'Lanos', 'Blue');
insert into model (id, model, brend, color) values (15, 1996, 'Ram Van 1500', 'Violet');
insert into model (id, model, brend, color) values (16, 2004, 'F-Series', 'Violet');
insert into model (id, model, brend, color) values (17, 1992, 'Continental Mark VII', 'Crimson');
insert into model (id, model, brend, color) values (18, 2004, 'XG350', 'Turquoise');
insert into model (id, model, brend, color) values (19, 2007, 'Tucson', 'Green');
insert into model (id, model, brend, color) values (20, 2006, 'H2 SUT', 'Puce');
insert into model (id, model, brend, color) values (21, 2006, 'Land Cruiser', 'Fuscia');
insert into model (id, model, brend, color) values (22, 2011, '7 Series', 'Red');
insert into model (id, model, brend, color) values (23, 2009, 'Sienna', 'Turquoise');
insert into model (id, model, brend, color) values (24, 1998, 'Altima', 'Indigo');
insert into model (id, model, brend, color) values (25, 1998, 'LSS', 'Orange');
insert into model (id, model, brend, color) values (26, 2001, 'Dakota', 'Crimson');
insert into model (id, model, brend, color) values (27, 1996, 'MPV', 'Mauv');
insert into model (id, model, brend, color) values (28, 2008, 'E-Series', 'Indigo');
insert into model (id, model, brend, color) values (29, 2006, 'GX', 'Teal');
insert into model (id, model, brend, color) values (30, 2011, 'Xterra', 'Blue');
insert into model (id, model, brend, color) values (31, 2012, 'Tahoe', 'Crimson');
insert into model (id, model, brend, color) values (32, 2009, 'XK', 'Maroon');
insert into model (id, model, brend, color) values (33, 2000, 'Trooper', 'Purple');
insert into model (id, model, brend, color) values (34, 2002, 'Econoline E250', 'Blue');
insert into model (id, model, brend, color) values (35, 2007, 'Uplander', 'Teal');
insert into model (id, model, brend, color) values (36, 1985, 'Bonneville', 'Crimson');
insert into model (id, model, brend, color) values (37, 1999, 'Mountaineer', 'Indigo');
insert into model (id, model, brend, color) values (38, 1992, 'Swift', 'Purple');
insert into model (id, model, brend, color) values (39, 1997, 'Ram Van 1500', 'Orange');
insert into model (id, model, brend, color) values (40, 1994, 'Cherokee', 'Blue');
insert into model (id, model, brend, color) values (41, 2007, 'SLR McLaren', 'Violet');
insert into model (id, model, brend, color) values (42, 1989, 'Continental Mark VII', 'Goldenrod');
insert into model (id, model, brend, color) values (43, 1996, 'Truck', 'Pink');
insert into model (id, model, brend, color) values (44, 1992, 'Fifth Ave', 'Fuscia');
insert into model (id, model, brend, color) values (45, 2006, 'Express', 'Teal');
insert into model (id, model, brend, color) values (46, 1997, 'Camaro', 'Crimson');
insert into model (id, model, brend, color) values (47, 1995, 'Avalon', 'Orange');
insert into model (id, model, brend, color) values (48, 1993, 'Eclipse', 'Violet');
insert into model (id, model, brend, color) values (49, 2008, 'Liberty', 'Orange');
insert into model (id, model, brend, color) values (50, 1993, 'Achieva', 'Violet');
insert into model (id, model, brend, color) values (51, 1998, 'Bravada', 'Goldenrod');
insert into model (id, model, brend, color) values (52, 1987, 'F-Series', 'Khaki');
insert into model (id, model, brend, color) values (53, 2012, 'C70', 'Purple');
insert into model (id, model, brend, color) values (54, 2001, 'S2000', 'Puce');
insert into model (id, model, brend, color) values (55, 1999, 'Avalon', 'Blue');
insert into model (id, model, brend, color) values (56, 1996, 'Maxima', 'Aquamarine');
insert into model (id, model, brend, color) values (57, 1994, 'Ram Wagon B250', 'Violet');
insert into model (id, model, brend, color) values (58, 1989, '911', 'Yellow');
insert into model (id, model, brend, color) values (59, 1992, 'Beretta', 'Maroon');
insert into model (id, model, brend, color) values (60, 2004, 'Aerio', 'Teal');
insert into model (id, model, brend, color) values (61, 2012, 'Canyon', 'Red');
insert into model (id, model, brend, color) values (62, 1988, 'Grand Am', 'Mauv');
insert into model (id, model, brend, color) values (63, 2006, '9-5', 'Yellow');
insert into model (id, model, brend, color) values (64, 2002, 'Aurora', 'Khaki');
insert into model (id, model, brend, color) values (65, 1995, 'S10', 'Maroon');
insert into model (id, model, brend, color) values (66, 2005, 'Ascender', 'Puce');
insert into model (id, model, brend, color) values (67, 1993, 'Cavalier', 'Khaki');
insert into model (id, model, brend, color) values (68, 2002, 'Prius', 'Red');
insert into model (id, model, brend, color) values (69, 2001, 'PT Cruiser', 'Violet');
insert into model (id, model, brend, color) values (70, 1997, 'XK Series', 'Turquoise');
insert into model (id, model, brend, color) values (71, 2009, 'Patriot', 'Mauv');
insert into model (id, model, brend, color) values (72, 2004, 'Lancer Evolution', 'Indigo');
insert into model (id, model, brend, color) values (73, 2007, 'Commander', 'Teal');
insert into model (id, model, brend, color) values (74, 1995, 'F350', 'Crimson');
insert into model (id, model, brend, color) values (75, 1996, '3500', 'Mauv');
insert into model (id, model, brend, color) values (76, 2006, 'Camry Solara', 'Orange');
insert into model (id, model, brend, color) values (77, 1992, 'F150', 'Khaki');
insert into model (id, model, brend, color) values (78, 1984, 'E-Class', 'Maroon');
insert into model (id, model, brend, color) values (79, 2004, 'C70', 'Green');
insert into model (id, model, brend, color) values (80, 2007, 'Canyon', 'Violet');
insert into model (id, model, brend, color) values (81, 1996, 'Caravan', 'Indigo');
insert into model (id, model, brend, color) values (82, 1987, '5000S', 'Yellow');
insert into model (id, model, brend, color) values (83, 1990, 'Sable', 'Green');
insert into model (id, model, brend, color) values (84, 2003, 'Outback', 'Red');
insert into model (id, model, brend, color) values (85, 2001, 'V40', 'Crimson');
insert into model (id, model, brend, color) values (86, 2001, 'Dakota Club', 'Turquoise');
insert into model (id, model, brend, color) values (87, 2012, 'LR4', 'Pink');
insert into model (id, model, brend, color) values (88, 1987, 'B-Series', 'Maroon');
insert into model (id, model, brend, color) values (89, 1996, 'Jimmy', 'Yellow');
insert into model (id, model, brend, color) values (90, 2007, 'Accent', 'Green');
insert into model (id, model, brend, color) values (91, 1992, 'Prelude', 'Khaki');
insert into model (id, model, brend, color) values (92, 1998, 'Voyager', 'Orange');
insert into model (id, model, brend, color) values (93, 1987, 'Gemini', 'Pink');
insert into model (id, model, brend, color) values (94, 2007, 'F150', 'Pink');
insert into model (id, model, brend, color) values (95, 1968, 'Bonneville', 'Purple');
insert into model (id, model, brend, color) values (96, 2005, 'LX', 'Aquamarine');
insert into model (id, model, brend, color) values (97, 2000, 'Villager', 'Crimson');
insert into model (id, model, brend, color) values (98, 2003, 'Vibe', 'Indigo');
insert into model (id, model, brend, color) values (99, 1995, 'G', 'Crimson');
insert into model (id, model, brend, color) values (100, 2003, '745', 'Purple');
