insert into racer (id, name, last_name, racing_id, team) values (1, 'Jae', 'Shevlane', '41-322-2054', 'China');
insert into racer (id, name, last_name, racing_id, team) values (2, 'Wilie', 'Haysman', '51-404-0707', 'China');
insert into racer (id, name, last_name, racing_id, team) values (3, 'Magnum', 'Tenpenny', '43-775-4716', 'South Africa');
insert into racer (id, name, last_name, racing_id, team) values (4, 'Cory', 'Platts', '83-438-5403', 'Ukraine');
insert into racer (id, name, last_name, racing_id, team) values (5, 'Hart', 'Jacobovitch', '60-368-1493', 'France');
insert into racer (id, name, last_name, racing_id, team) values (6, 'Osbourne', 'Dy', '15-206-5681', 'Mexico');
insert into racer (id, name, last_name, racing_id, team) values (7, 'Vere', 'Radcliffe', '43-818-5834', 'China');
insert into racer (id, name, last_name, racing_id, team) values (8, 'Amanda', 'Cornell', '96-926-6217', 'China');
insert into racer (id, name, last_name, racing_id, team) values (9, 'Adrian', 'Benza', '13-224-9963', 'Malaysia');
insert into racer (id, name, last_name, racing_id, team) values (10, 'Claudia', 'Nuttall', '96-368-5121', 'Ukraine');
insert into racer (id, name, last_name, racing_id, team) values (11, 'Goldina', 'Pentelo', '99-641-7046', 'China');
insert into racer (id, name, last_name, racing_id, team) values (12, 'Tisha', 'Pioli', '70-123-3321', 'Brazil');
insert into racer (id, name, last_name, racing_id, team) values (13, 'Trent', 'Haylor', '72-437-2976', 'China');
insert into racer (id, name, last_name, racing_id, team) values (14, 'Leland', 'Plunket', '93-457-5384', 'Democratic Republic of the Congo');
insert into racer (id, name, last_name, racing_id, team) values (15, 'Dione', 'Dunklee', '37-507-8900', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (16, 'Burlie', 'Pridmore', '88-598-4400', 'France');
insert into racer (id, name, last_name, racing_id, team) values (17, 'Bruno', 'Desbrow', '43-088-1532', 'Mauritius');
insert into racer (id, name, last_name, racing_id, team) values (18, 'Ivy', 'Grealey', '85-712-3889', 'Russia');
insert into racer (id, name, last_name, racing_id, team) values (19, 'Jerrilee', 'Whitcomb', '33-154-7056', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (20, 'Moishe', 'Izen', '46-641-5465', 'Mexico');
insert into racer (id, name, last_name, racing_id, team) values (21, 'Estella', 'Linggood', '05-841-1783', 'Spain');
insert into racer (id, name, last_name, racing_id, team) values (22, 'Nichol', 'Scoates', '17-648-4177', 'Kazakhstan');
insert into racer (id, name, last_name, racing_id, team) values (23, 'Sadye', 'Harms', '73-731-0462', 'Poland');
insert into racer (id, name, last_name, racing_id, team) values (24, 'Madelon', 'Hobble', '16-938-9576', 'China');
insert into racer (id, name, last_name, racing_id, team) values (25, 'Austine', 'Rennison', '84-618-7753', 'China');
insert into racer (id, name, last_name, racing_id, team) values (26, 'Lois', 'Gauld', '27-149-2775', 'Brazil');
insert into racer (id, name, last_name, racing_id, team) values (27, 'Lucho', 'Byrnes', '20-248-2017', 'China');
insert into racer (id, name, last_name, racing_id, team) values (28, 'Rowan', 'Wynett', '30-173-1823', 'Russia');
insert into racer (id, name, last_name, racing_id, team) values (29, 'Katharyn', 'McGriele', '34-003-2580', 'China');
insert into racer (id, name, last_name, racing_id, team) values (30, 'Stern', 'Rand', '03-405-2389', 'United Kingdom');
insert into racer (id, name, last_name, racing_id, team) values (31, 'Minnnie', 'Pigne', '35-155-4805', 'China');
insert into racer (id, name, last_name, racing_id, team) values (32, 'Rachel', 'Bridgeman', '96-615-6580', 'Ukraine');
insert into racer (id, name, last_name, racing_id, team) values (33, 'Lulita', 'Gebhardt', '91-451-3365', 'China');
insert into racer (id, name, last_name, racing_id, team) values (34, 'Eric', 'Jowitt', '75-738-9171', 'Bulgaria');
insert into racer (id, name, last_name, racing_id, team) values (35, 'Jori', 'Keggin', '63-786-5521', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (36, 'Wendall', 'Eveque', '99-679-8368', 'Finland');
insert into racer (id, name, last_name, racing_id, team) values (37, 'Corrie', 'Adnet', '21-518-9629', 'China');
insert into racer (id, name, last_name, racing_id, team) values (38, 'Beverley', 'Durdy', '58-669-9318', 'China');
insert into racer (id, name, last_name, racing_id, team) values (39, 'Theodore', 'Hairsnape', '99-876-3659', 'Czech Republic');
insert into racer (id, name, last_name, racing_id, team) values (40, 'Fay', 'Joselevitch', '55-658-9083', 'South Africa');
insert into racer (id, name, last_name, racing_id, team) values (41, 'Zarla', 'Rohloff', '96-465-2201', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (42, 'Conchita', 'Dahlgren', '79-565-4311', 'China');
insert into racer (id, name, last_name, racing_id, team) values (43, 'Juli', 'Meeny', '96-857-8699', 'France');
insert into racer (id, name, last_name, racing_id, team) values (44, 'Jonathan', 'Snoad', '01-162-7294', 'Thailand');
insert into racer (id, name, last_name, racing_id, team) values (45, 'Courtnay', 'Tousey', '56-435-2473', 'China');
insert into racer (id, name, last_name, racing_id, team) values (46, 'Beverlee', 'Panniers', '08-026-0224', 'Puerto Rico');
insert into racer (id, name, last_name, racing_id, team) values (47, 'Elvina', 'Jereatt', '99-630-7040', 'Thailand');
insert into racer (id, name, last_name, racing_id, team) values (48, 'Maurene', 'Hazelden', '74-931-2903', 'Argentina');
insert into racer (id, name, last_name, racing_id, team) values (49, 'Lon', 'Boschmann', '08-289-3283', 'Portugal');
insert into racer (id, name, last_name, racing_id, team) values (50, 'Tam', 'O''Kennedy', '62-015-6604', 'Argentina');
insert into racer (id, name, last_name, racing_id, team) values (51, 'Hilliard', 'Menci', '62-453-2875', 'Mexico');
insert into racer (id, name, last_name, racing_id, team) values (52, 'Derrik', 'Genders', '61-068-7454', 'Poland');
insert into racer (id, name, last_name, racing_id, team) values (53, 'Marietta', 'Cossam', '79-002-9047', 'Russia');
insert into racer (id, name, last_name, racing_id, team) values (54, 'Maje', 'Meaker', '81-441-8259', 'Greece');
insert into racer (id, name, last_name, racing_id, team) values (55, 'Tamra', 'Bunyard', '73-666-3577', 'United States');
insert into racer (id, name, last_name, racing_id, team) values (56, 'Inge', 'Mattiato', '63-423-2691', 'Brazil');
insert into racer (id, name, last_name, racing_id, team) values (57, 'Yetty', 'Erb', '22-430-1097', 'Nicaragua');
insert into racer (id, name, last_name, racing_id, team) values (58, 'Conrade', 'Matyja', '77-946-2810', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (59, 'Laurel', 'Kiely', '01-728-6713', 'Cuba');
insert into racer (id, name, last_name, racing_id, team) values (60, 'Florence', 'Santello', '50-296-8653', 'Czech Republic');
insert into racer (id, name, last_name, racing_id, team) values (61, 'Sydelle', 'Payler', '14-721-2456', 'Israel');
insert into racer (id, name, last_name, racing_id, team) values (62, 'Axel', 'Yegorev', '68-806-7796', 'Armenia');
insert into racer (id, name, last_name, racing_id, team) values (63, 'Maxwell', 'Tibbs', '12-259-1238', 'China');
insert into racer (id, name, last_name, racing_id, team) values (64, 'Hillary', 'Hatchette', '02-657-5482', 'United States');
insert into racer (id, name, last_name, racing_id, team) values (65, 'Wilone', 'Kobke', '56-588-4820', 'Azerbaijan');
insert into racer (id, name, last_name, racing_id, team) values (66, 'Hube', 'Lermit', '56-189-0297', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (67, 'Grethel', 'Bootman', '86-216-5104', 'China');
insert into racer (id, name, last_name, racing_id, team) values (68, 'Levon', 'Mockes', '14-609-8401', 'Peru');
insert into racer (id, name, last_name, racing_id, team) values (69, 'Ike', 'Kilmaster', '26-457-3063', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (70, 'Kippy', 'Meeks', '04-454-7922', 'Mexico');
insert into racer (id, name, last_name, racing_id, team) values (71, 'Kennith', 'Kellington', '61-101-0123', 'China');
insert into racer (id, name, last_name, racing_id, team) values (72, 'Adina', 'Arrighetti', '02-531-9724', 'Portugal');
insert into racer (id, name, last_name, racing_id, team) values (73, 'Germain', 'Ogborne', '42-198-2541', 'Canada');
insert into racer (id, name, last_name, racing_id, team) values (74, 'Brook', 'Tregien', '16-068-9596', 'Japan');
insert into racer (id, name, last_name, racing_id, team) values (75, 'Rocky', 'Sabey', '63-610-9853', 'Czech Republic');
insert into racer (id, name, last_name, racing_id, team) values (76, 'Onfre', 'Oby', '28-327-6885', 'Brazil');
insert into racer (id, name, last_name, racing_id, team) values (77, 'Viviene', 'Sarra', '37-473-0799', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (78, 'Gal', 'Gotcliffe', '95-500-3372', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (79, 'Portie', 'Grieswood', '05-155-6060', 'Russia');
insert into racer (id, name, last_name, racing_id, team) values (80, 'Jaime', 'Mulrean', '07-526-7971', 'Paraguay');
insert into racer (id, name, last_name, racing_id, team) values (81, 'Rafaello', 'Letford', '01-414-5573', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (82, 'Tomkin', 'Elsip', '98-043-8570', 'Guatemala');
insert into racer (id, name, last_name, racing_id, team) values (83, 'Sosanna', 'Cinnamond', '54-474-7139', 'Nigeria');
insert into racer (id, name, last_name, racing_id, team) values (84, 'Shari', 'Lindfors', '67-612-2763', 'Sweden');
insert into racer (id, name, last_name, racing_id, team) values (85, 'Odelle', 'Hedditeh', '82-879-7207', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (86, 'Banky', 'Bodle', '67-501-9979', 'China');
insert into racer (id, name, last_name, racing_id, team) values (87, 'Demetri', 'Atyeo', '74-027-6295', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (88, 'Carlee', 'Sinkings', '25-421-7870', 'China');
insert into racer (id, name, last_name, racing_id, team) values (89, 'Rad', 'Labusch', '69-913-4942', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (90, 'Bee', 'Dommerque', '20-416-6214', 'Malaysia');
insert into racer (id, name, last_name, racing_id, team) values (91, 'Cory', 'Lisamore', '46-076-6422', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (92, 'Lazare', 'Deakan', '52-665-3949', 'Philippines');
insert into racer (id, name, last_name, racing_id, team) values (93, 'Archibald', 'Orteau', '95-109-2751', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (94, 'Sue', 'Dalton', '48-412-8684', 'France');
insert into racer (id, name, last_name, racing_id, team) values (95, 'Dom', 'Brognot', '10-284-0568', 'China');
insert into racer (id, name, last_name, racing_id, team) values (96, 'Chantal', 'Boate', '72-125-0604', 'Argentina');
insert into racer (id, name, last_name, racing_id, team) values (97, 'Terri', 'Foxley', '60-246-2748', 'Indonesia');
insert into racer (id, name, last_name, racing_id, team) values (98, 'Vinnie', 'Torrejon', '45-178-8236', 'Guatemala');
insert into racer (id, name, last_name, racing_id, team) values (99, 'Gregg', 'Leonida', '65-944-5000', 'China');
insert into racer (id, name, last_name, racing_id, team) values (100, 'Stephanus', 'Barbier', '65-708-8220', 'Nepal');
